apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scc-state
spec:
  replicas: 1 # Leave this as 1 - This service is a singleton.
  template:
    metadata:
      labels:
        app: scc-state
    spec:
      containers:
      - name: scc-state
        image: socketcluster/scc-state:v1.5.2
        ports:
        - containerPort: 7777
        livenessProbe:
          httpGet:
            path: /health-check
            port: 7777
          initialDelaySeconds: 15
          timeoutSeconds: 5
